(*implemented methods:
User.getEvents
User.getFriends
User.getInfo
User.getLovedTracks
User.getNeighbours
User.getPastEvents
User.getPlaylists
User.getRecentStations
User.getRecentTracks
User.getRecommendedArtists
User.getRecommendedEvents
User.getShouts
User.getTopAlbums
User.getTopArtists
User.getTopTags
User.getTopTracks
User.getWeeklyAlbumChart
User.getWeeklyArtistChart
User.getWeeklyChartList
User.getWeeklyTrackChart
User.shout*)